name: finalltmcb
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  url_strategy: ^0.3.0
  shared_preferences: ^2.2.2
  universal_html: ^2.2.4
  carousel_slider: ^5.0.0
  intl: ^0.20.2
  image_picker: ^1.0.7 # Để chọn ảnh/video từ thư viện/camera
  video_player: ^2.8.3 # Để phát video
  chewie: ^1.7.5 # Giao diện điều khiển cho video_player
  audioplayers: ^5.2.1 # Updated to newer version as suggested
  record: ^6.0.0 # Using older version to avoid abstract class issues
  path_provider: ^2.1.1 # Add or update this line
  permission_handler: ^11.3.0 # Yêu cầu quyền truy cập (camera, mic, storage)
  uuid: ^4.3.3 # 
  file_picker: ^5.2.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # Add assets with proper indentation (this section was incorrectly indented in your file)
  assets:
    - assets/
    - assets/mouseBanner.jpg
    - assets/product1.jpg
    - assets/product2.jpg
    - assets/p4.jpg
    - assets/product3.jpg
    - assets/banner.jpg
    - assets/logoS.jpg
    - assets/logoS-removebg-preview.png
    - assets/logoSNew.png
    - assets/banner2.jpg
    - assets/banner3.jpg
    - assets/banner4.jpg
    - assets/banner5.jpg
    - assets/banner5N.jpg
    - assets/banner6.jpg
    - assets/banner7.jpg
    - assets/bannerMain.jpg